# Generated by Django 5.0.4 on 2024-04-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='name',
            new_name='computer_specification',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='computer',
            new_name='computer_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='membership',
        ),
        migrations.AddField(
            model_name='computer',
            name='computer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.CharField(choices=[('Aadhar', 'AADHAR'), ('Pam', 'PAN'), ('Voter', 'VOTER')], default='Aadhar', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
