# Generated by Django 5.0.4 on 2024-04-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_reservation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_proof',
            field=models.CharField(choices=[('Aadhar', 'AADHAR'), ('Pan', 'PAN'), ('Voter', 'VOTER')], default='Aadhar', max_length=6, null=True),
        ),
    ]
