# f = open('myfile.txt','r')
# print(f)
# text = f.read()
# print(text)
# f.close()
# f = open('myfile.txt','w')
# f.write("i am intelligent")
# f = open('myfile.txt','a')
# f.write("i am good")
# f = open('myfile2.txt','x')
# f = open('myfile2.txt','a')
# f.write(" I am Python Intern.")